version: 2.1
workflows:
  version: 2
  just_push:
      jobs:
      - pantheon/push
  tests:
    jobs:
      - ci-tools/lighthouse:
          url: 'http://prolificsys.com'

orbs:
  pantheon: pantheon-systems/pantheon@0.5.1
  ci-tools: kanopi/ci-tools@1.4.10